### ISSUE TITLE
Add support for --dual-color

### ISSUE THREAD

**Issue by kyleam** [magit/magit-tbdiff#3]
Both tbdiff and range-diff have a --dual-color switch that can make it easier to digest the diff of diffs.  Adding support for it boils down to parsing range-diff's or tbdiff's ansi escape sequences, making it the same problem as supporting diff's --color-moved (magit/magit#3424).

**Comment by afrepues** [comment]
Magit introduced support for `--color-moved` on magit/magit@9d0e65ee364009c51ddadf1e2a71c2104290d4ac.

**Comment by kyleam** [comment]
Thanks, @afrepues.  I haven't yet taken a closer look, but I've bumped it up the to-do list.
