### ISSUE TITLE
Suggestion: have similar coloring as "git range-diff --dual-color"

### ISSUE THREAD

**Issue by geza-herman** [magit/magit-tbdiff#6]
Would it be possible to have coloring similar to --dual-color? Currently, the diff is colored like --no-dual-color. If we diff the ranges `a1..b1` and `a2..b2`, the diff colored according to changes between a1..a2 or b1..b2, and not according to the actual changes between a1..a2 and b1..b2.

**Comment by kyleam** [comment]
`--dual-color` has been in the transient since da1ea84 (Support range-diff's --dual-color, 2019-04-21), assuming you use `git-range-diff` rather than `git-tbdiff` (as it seems you do, based on the title).  I don't have that option on by default, but I do use it fairly often.  The only issue I've noticed is that in some cases the dual-coloring bleeds into the hunk headers, but I haven't figured out what's going on there.

**Comment by geza-formlabs** [comment]
Ah, now I see. I just used it from lisp, I didn't notice that it has transient interface as well. With `--dual-color` turned on, the colors are better, but I think that it still could be improved.

 `git range-diff` doesn't color parts, where the '+'/'-' sign in the first column, it just bolds these areas. And it colors parts, where '+'/'-' is in the second column. So, these colored parts shows the actual difference. With `magit-tbdiff`, it uses background colors for the first column (so it is visually strong), and for the second column, it uses the same technique as `git range-diff` (color the foreground).

Would it be possible to disable coloring for the first column? Or, maybe it would be better, if we could swap the coloring technique of the first and second column. So the actual differences would have background colors. What do you think?

**Comment by geza-herman** [comment]
Ah, now I see. I just used it from lisp, I didn't notice that it has transient interface as well. With `--dual-color` turned on, the colors are better, but I think that it still could be improved.

 `git range-diff` doesn't color parts, where the '+'/'-' sign in the first column, it just bolds these areas. And it colors parts, where '+'/'-' is in the second column. So, these colored parts shows the actual difference. With `magit-tbdiff`, it uses background colors for the first column (so it is visually strong), and for the second column, it uses the same technique as `git range-diff` (color the foreground).

Would it be possible to disable coloring for the first column? Or, maybe it would be better, if we could swap the coloring technique of the first and second column. So the actual differences would have background colors. What do you think?

**Comment by kyleam** [comment]
> `git range-diff` doesn't color parts [...]

Hopefully these images capture what you're describing (sorry for the slightly different sizes and for the difference in my terminal/emacs background color).

range-diff:
![0c](https://user-images.githubusercontent.com/1297788/82006166-2cf66600-9635-11ea-9fd4-255c82116cfe.png)
magit-tbdiff
![1c](https://user-images.githubusercontent.com/1297788/82006179-354ea100-9635-11ea-8def-434c6cebf87d.png)

The main difference I see is that magit-tbdiff maps the inverted colors in the outer column to boxes.  Here's what I had to say about this in da1ea84:

```
  * range-diff --dual-color shows the output diff markers as inverted.
    ansi-color doesn't handle this in a way that is useful for our
    purposes because it maps the inverted colors to the error face.

    Instead put a box around the inverted text.
```

> Would it be possible to disable coloring for the first column? 

Do you mean disabling the color entirely?  Or do you mean keeping the color border but removing the foreground color from the outer -/+?  I wouldn't be in favor of the former, as I think some form of dual coloring is better than coloring the inner diff alone.  I'd be fine with the latter, or with going for an outer marker appearance that is closer to range-diff in terms of inverting foreground/background.  I just didn't see a good way to do that, but perhaps another look would reveal something.  Any suggestions on how to coax `ansi-color-apply-on-region` into that behavior would of course be appreciated.

> Or, maybe it would be better, if we could swap the coloring technique of the first and second column.  So the actual differences would have background colors. What do you think?

Hmm, that makes me think you're seeing something very different than I am!  Can you post some images?

In any case, I certainly agree that visually there's room for improvement.  It's just a question of how to do it.  What I landed on was the best approach I could come up with at the time.  (And, as I mentioned in my initial post, there is also at least one bug where some color leaks up until it hits the hunk header.)

**Comment by geza-herman** [comment]
Your screenshots look good to me, they are clear. Mine are a little bit different, because of background colors. Here's a screenshot of `git range-diff`:
![screenshot000039](https://user-images.githubusercontent.com/27892988/82042987-1c80d280-96ab-11ea-9825-40566494a86d.png)

The line that's important for me, is the `this_line_is_added_during_rebase()` (I use the range-diff feature for verifying my modifications during a rebase). As you can see, this line is the most visually prominent. Just like in your screenshots.

Now, the same thing in emacs:
![screenshot000040](https://user-images.githubusercontent.com/27892988/82043321-b2b4f880-96ab-11ea-86d8-ed68c807b1b7.png)

As you can see, there are background colors added, but not where I'd expect them. It seems that background colors are added as if this buffer were a "simple" diff buffer (so it has nothing to do with magit-tbdiff).

I'm not sure what would be the best solution. Maybe only add the background, if both columns have the same marker? I'm not too experienced with range-diff, so maybe this idea is not 100% correct in all cases (but it would solve my `this_line_is_added_during_rebase()` case).

**Comment by kyleam** [comment]
Thanks.  Those images are helpful.  I'll try to find time soon to revisit this and will test/consider dark backgrounds when I do.

**Comment by kyleam** [comment]
I've pushed to the dual-color-rework branch (a6905b4).  I need to think more about it, but if you have time to give that a try, let me know how the `--dual-color` output looks on your end.

**Comment by geza-formlabs** [comment]
Now it looks pretty much the same as the `git range-diff` version, it's a definite improvement for me, thanks!

![screenshot000041](https://user-images.githubusercontent.com/51319552/82203737-fa35c180-9903-11ea-83cf-2f749085516b.png)

**Comment by geza-herman** [comment]
Now it looks pretty much the same as the `git range-diff` version, it's a definite improvement for me, thanks!

![screenshot000041](https://user-images.githubusercontent.com/27892988/82204116-9cee4000-9904-11ea-9d50-7d2e7cbdd855.png)
